version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    #env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD:root
      - MYSQL_DATABASE:test
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql


volumes:
  db: